<?php

declare(strict_types=1);

use Dotdigitalgroup\Sms\ViewModel\TelephoneInputConfig;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var TelephoneInputConfig $telephoneInputConfig
 * @var Escaper $escaper
 * @var HyvaCsp $hyvaCsp
 */
$telephoneInputConfig = $block->getData('telephoneInputConfig');
?>
<script type="module">
    import '<?= $escaper->escapeJs($block->getViewFileUrl('Dotdigitalgroup_Sms::js/intlTelInput.js')) ?>';
    import {
        validationRule,
        intlInput,
        includeStyle
    } from '<?= $escaper->escapeJs($block->getViewFileUrl('Hyva_DotdigitalgroupSms::js/intl-input-validation.js')) ?>';
    window.addEventListener('alpine:init', () => hyva.formValidation.addRule(
        'validate-phone-number-with-checkbox',
        validationRule
    ));
    window.addEventListener('alpine:initialized', () => {
        includeStyle('<?= $escaper->escapeJs($block->getViewFileUrl('Dotdigitalgroup_Sms::css/hyva.css')) ?>');
        <?php if ($telephoneInputConfig->isRequired()) { ?>
        intlInput(
            "input[name='telephone']",
            JSON.parse("<?= $escaper->escapeJs($telephoneInputConfig->getConfig()); ?>"),
            ["required"]
        )
        <?php } else { ?>
        intlInput(
            "input[name='telephone']",
            JSON.parse("<?= $escaper->escapeJs($telephoneInputConfig->getConfig()); ?>"),
            [],
            false
        )
        <?php } ?>
    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>
